/*
 * The MIT License
 *
 * Copyright 2023 Nirbhay Pundir.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package parkingschedular.user;

import parkingschedular.ParkingSchedular;
import parkingschedular.utility.UserDetails;
import parkingschedular.utility.Utility;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.time.Duration;
import java.time.LocalDateTime;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import parkingschedular.utility.Time;

/**
 *
 * @author Nirbhay Pundir
 */
public class UserDashboardGUI extends javax.swing.JFrame {

    Utility u;
    Time t;
    UserDetails UD;

    public UserDashboardGUI() {
        u = new Utility();
        initComponents();
        u.setCorners(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vehicleTypeGroup = new javax.swing.ButtonGroup();
        releaseSlot = new javax.swing.JDialog();
        selectedSlotL = new javax.swing.JLabel();
        slotsMenu = new javax.swing.JComboBox<>();
        chargeLabel = new javax.swing.JLabel();
        chargeLabel1 = new javax.swing.JLabel();
        payBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel() {
            protected void paintComponent(Graphics grphcs) {
                super.paintComponent(grphcs);
                Graphics2D g2d = (Graphics2D) grphcs;
                g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                    RenderingHints.VALUE_ANTIALIAS_ON);
                GradientPaint gp = new GradientPaint(0, getHeight(),
                    getBackground().brighter().brighter(), 0, 0,
                    getBackground().darker());
                g2d.setPaint(gp);
                g2d.fillRect(0, 0, getWidth(), getHeight()); 

            }
        };
        btnClose = new javax.swing.JLabel();
        tittle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        vehicle = new javax.swing.JLabel();
        vehicleText = new javax.swing.JTextField();
        vehicleType = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        carRadio = new parkingschedular.utility.RadioButtonCustom();
        motorcycleRadio = new parkingschedular.utility.RadioButtonCustom();
        date = new javax.swing.JLabel();
        dateText = new javax.swing.JFormattedTextField();
        time = new javax.swing.JLabel();
        timeText = new javax.swing.JFormattedTextField();
        slot = new javax.swing.JLabel();
        slotText = new javax.swing.JTextField();
        bookBtn = new javax.swing.JButton();
        clock = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        releaseBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        Lname = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        Lvehicle = new javax.swing.JLabel();
        Vehicle = new javax.swing.JLabel();
        Lemail = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        lPhone = new javax.swing.JLabel();
        Phone = new javax.swing.JLabel();
        updateDetails = new javax.swing.JButton();
        logOut = new javax.swing.JButton();
        chargeL = new javax.swing.JLabel();
        chargeT = new javax.swing.JLabel();
        timeL = new javax.swing.JLabel();
        timeT = new javax.swing.JLabel();
        dateL = new javax.swing.JLabel();
        dateT = new javax.swing.JLabel();

        releaseSlot.setResizable(false);

        selectedSlotL.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        selectedSlotL.setForeground(new java.awt.Color(102, 102, 102));
        selectedSlotL.setText("Selected Slot:");

        slotsMenu.setBackground(new java.awt.Color(100, 221, 143));
        slotsMenu.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        slotsMenu.setForeground(new java.awt.Color(255, 255, 255));
        slotsMenu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                slotsMenuFocusGained(evt);
            }
        });
        slotsMenu.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                slotsMenuPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        chargeLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        chargeLabel.setForeground(new java.awt.Color(153, 153, 153));
        chargeLabel.setText("Rs. 40");

        chargeLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        chargeLabel1.setForeground(new java.awt.Color(102, 102, 102));
        chargeLabel1.setText("Total Charge:");

        payBtn.setBackground(ParkingSchedular.buttonColor);
        payBtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        payBtn.setForeground(new java.awt.Color(204, 255, 255));
        payBtn.setText("Pay");
        payBtn.setBorder(null);
        payBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                payBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                payBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout releaseSlotLayout = new javax.swing.GroupLayout(releaseSlot.getContentPane());
        releaseSlot.getContentPane().setLayout(releaseSlotLayout);
        releaseSlotLayout.setHorizontalGroup(
            releaseSlotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(releaseSlotLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(releaseSlotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(selectedSlotL)
                    .addComponent(chargeLabel1))
                .addGap(18, 18, 18)
                .addGroup(releaseSlotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chargeLabel)
                    .addComponent(slotsMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, releaseSlotLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(payBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        releaseSlotLayout.setVerticalGroup(
            releaseSlotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, releaseSlotLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(releaseSlotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(slotsMenu)
                    .addComponent(selectedSlotL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(releaseSlotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chargeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chargeLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(payBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(u.iconImage);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 252, 52));
        jPanel1.setMaximumSize(new java.awt.Dimension(810, 440));
        jPanel1.setMinimumSize(new java.awt.Dimension(810, 440));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        btnClose.setText("hhferv");
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExit(evt);
            }
        });

        tittle.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 36)); // NOI18N
        tittle.setForeground(new java.awt.Color(204, 255, 255));
        tittle.setIcon(u.icon);
        tittle.setText("Parking Schedular");

        jPanel2.setBackground(ParkingSchedular.panelColor);
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 221, 225), 2), "Book Slot", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Light", 0, 36), new java.awt.Color(204, 255, 255))); // NOI18N

        name.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        name.setForeground(new java.awt.Color(217, 255, 252));
        name.setText("Name:");

        nameText.setBackground(new java.awt.Color(100, 221, 143));
        nameText.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        nameText.setForeground(new java.awt.Color(255, 255, 255));
        nameText.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 255, 255)), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        nameText.setCaretColor(new java.awt.Color(204, 255, 255));
        nameText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameTextFocusLost(evt);
            }
        });

        vehicle.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        vehicle.setForeground(new java.awt.Color(217, 255, 252));
        vehicle.setText("Vehicle Number:");

        vehicleText.setBackground(new java.awt.Color(100, 221, 143));
        vehicleText.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        vehicleText.setForeground(new java.awt.Color(255, 255, 255));
        vehicleText.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 255, 255)), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        vehicleText.setCaretColor(new java.awt.Color(204, 255, 255));
        vehicleText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                vehicleTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                vehicleTextFocusLost(evt);
            }
        });

        vehicleType.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        vehicleType.setForeground(new java.awt.Color(217, 255, 252));
        vehicleType.setText("Vehicle Type:");

        jPanel5.setBackground(nameText.getBackground());

        carRadio.setBackground(nameText.getBackground());
        carRadio.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        vehicleTypeGroup.add(carRadio);
        carRadio.setForeground(new java.awt.Color(255, 255, 255));
        carRadio.setSelected(true);
        carRadio.setText("Car");
        carRadio.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        motorcycleRadio.setBackground(nameText.getBackground());
        motorcycleRadio.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        vehicleTypeGroup.add(motorcycleRadio);
        motorcycleRadio.setForeground(new java.awt.Color(255, 255, 255));
        motorcycleRadio.setText("Motorcycle");
        motorcycleRadio.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(carRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(motorcycleRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(motorcycleRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        date.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        date.setForeground(new java.awt.Color(217, 255, 252));
        date.setText("Arrival Date:");

        dateText.setBackground(new java.awt.Color(100, 221, 143));
        dateText.setBorder(nameText.getBorder());
        dateText.setForeground(new java.awt.Color(255, 255, 255));
        dateText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        dateText.setText("01/04/23");
        dateText.setCaretColor(new java.awt.Color(204, 255, 255));
        dateText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dateTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dateTextFocusLost(evt);
            }
        });

        time.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        time.setForeground(new java.awt.Color(217, 255, 252));
        time.setText("Arrival Time:");

        timeText.setBackground(new java.awt.Color(100, 221, 143));
        timeText.setBorder(nameText.getBorder());
        timeText.setForeground(new java.awt.Color(255, 255, 255));
        timeText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance())));
        timeText.setText("01:15:16 PM");
        timeText.setToolTipText("");
        timeText.setCaretColor(new java.awt.Color(204, 255, 255));
        timeText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                timeTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                timeTextFocusLost(evt);
            }
        });

        slot.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        slot.setForeground(new java.awt.Color(217, 255, 252));
        slot.setText("Assigned Slot:");

        slotText.setEditable(false);
        slotText.setBackground(new java.awt.Color(100, 221, 143));
        slotText.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        slotText.setForeground(new java.awt.Color(255, 255, 255));
        slotText.setText("1");
        slotText.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 255, 255)), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        slotText.setCaretColor(new java.awt.Color(204, 255, 255));

        bookBtn.setBackground(ParkingSchedular.buttonColor);
        bookBtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        bookBtn.setForeground(new java.awt.Color(204, 255, 255));
        bookBtn.setText("Book Slot");
        bookBtn.setBorder(null);
        bookBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookBtnMouseExited(evt);
            }
        });

        clock.setText("hhv");
        clock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clockMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameText)
                    .addComponent(vehicleText)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date)
                            .addComponent(name)
                            .addComponent(vehicle)
                            .addComponent(vehicleType)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clock, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(timeText, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(time)))
                    .addComponent(slotText)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(slot)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vehicle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vehicleText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vehicleType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(date)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clock)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(time)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timeText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(slot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(slotText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(bookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        clock.setIcon(u.imageClock);
        clock.setText("");

        jPanel3.setBackground(ParkingSchedular.panelColor);
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 221, 225), 2), "Bookings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Light", 0, 36), new java.awt.Color(204, 255, 255))); // NOI18N

        jPanel6.setOpaque(false);

        jScrollPane1.setBorder(null);
        jScrollPane1.setOpaque(false);

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Slot", "Name", "Vehicle Number", "Arrival Time", "Vehicle Type", "Payment"
            }
        ));
        userTable.setDropMode(javax.swing.DropMode.ON);
        userTable.setEnabled(false);
        userTable.setFocusable(false);
        userTable.setGridColor(new Color(0,0,0,0));
        userTable.setOpaque(false);
        userTable.setRowHeight(60);
        userTable.setSelectionBackground(new java.awt.Color(0, 214, 34));
        userTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(userTable);
        u.table(userTable);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        releaseBtn.setBackground(ParkingSchedular.buttonColor);
        releaseBtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        releaseBtn.setForeground(new java.awt.Color(204, 255, 255));
        releaseBtn.setText("Release Slot");
        releaseBtn.setBorder(null);
        releaseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                releaseBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                releaseBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                releaseBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(releaseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(releaseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(ParkingSchedular.panelColor);
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 221, 225), 2), "User Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Light", 0, 36), new java.awt.Color(204, 255, 255))); // NOI18N

        Lname.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        Lname.setForeground(new java.awt.Color(204, 204, 204));
        Lname.setText("Name:");

        Name.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        Name.setForeground(new java.awt.Color(217, 255, 252));
        Name.setText("Name");

        Lvehicle.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        Lvehicle.setForeground(new java.awt.Color(204, 204, 204));
        Lvehicle.setText("Vehicle Number:");

        Vehicle.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        Vehicle.setForeground(new java.awt.Color(217, 255, 252));
        Vehicle.setText("vehicle");

        Lemail.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        Lemail.setForeground(new java.awt.Color(204, 204, 204));
        Lemail.setText("Email:");

        Email.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        Email.setForeground(new java.awt.Color(217, 255, 252));
        Email.setText("nirbhayrajput003@gmail.com");

        lPhone.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        lPhone.setForeground(new java.awt.Color(204, 204, 204));
        lPhone.setText("Phone:");

        Phone.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        Phone.setForeground(new java.awt.Color(217, 255, 252));
        Phone.setText("8979061210");

        updateDetails.setBackground(ParkingSchedular.buttonColor);
        updateDetails.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        updateDetails.setForeground(new java.awt.Color(204, 255, 255));
        updateDetails.setText("Update Details");
        updateDetails.setBorder(null);
        updateDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateDetailsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateDetailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateDetailsMouseExited(evt);
            }
        });

        logOut.setBackground(ParkingSchedular.buttonColor);
        logOut.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        logOut.setForeground(new java.awt.Color(204, 255, 255));
        logOut.setText("Log Out");
        logOut.setBorder(null);
        logOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Lvehicle)
                    .addComponent(Lname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Vehicle, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lemail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(89, 89, 89)
                        .addComponent(logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Phone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(123, 123, 123)
                        .addComponent(updateDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lname)
                            .addComponent(Name)
                            .addComponent(Lemail)
                            .addComponent(Email))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lvehicle)
                            .addComponent(Vehicle)
                            .addComponent(lPhone)
                            .addComponent(Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        chargeL.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        chargeL.setForeground(new java.awt.Color(204, 204, 204));
        chargeL.setText("Charge(per hour):");

        chargeT.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        chargeT.setForeground(new java.awt.Color(217, 255, 252));
        chargeT.setText("Rs. 40");
        chargeT.setToolTipText("");

        timeL.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        timeL.setForeground(new java.awt.Color(204, 204, 204));
        timeL.setText("Time:");

        timeT.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        timeT.setForeground(new java.awt.Color(217, 255, 252));
        timeT.setText("01:15:16 PM");
        timeT.setToolTipText("");

        dateL.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        dateL.setForeground(new java.awt.Color(204, 204, 204));
        dateL.setText("Date:");

        dateT.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        dateT.setForeground(new java.awt.Color(217, 255, 252));
        dateT.setText("07/05/2023");
        dateT.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(492, 492, 492)
                        .addComponent(dateL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateT, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(timeL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timeT, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chargeL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chargeT)
                        .addGap(115, 115, 115)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tittle)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClose)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(timeL)
                                .addComponent(timeT)
                                .addComponent(dateL)
                                .addComponent(dateT)
                                .addComponent(chargeL)
                                .addComponent(chargeT)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnClose.setIcon(u.imageClose);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutMouseClicked
        ParkingSchedular.Email = null;
        u.switchFrame(this, ParkingSchedular.lg);
        t.stop();
        UD.logout();
    }//GEN-LAST:event_logOutMouseClicked

    private void logOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutMouseEntered
        if (logOut.isEnabled()) {
            logOut.setBackground(ParkingSchedular.enterButtonColor);
        }
    }//GEN-LAST:event_logOutMouseEntered

    private void logOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutMouseExited
        if (logOut.isEnabled()) {
            logOut.setBackground(ParkingSchedular.buttonColor);
        }
    }//GEN-LAST:event_logOutMouseExited

    private void releaseBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_releaseBtnMouseClicked
        releaseSlot.setTitle("Payment");
        releaseSlot.setSize(350, 200);
        releaseSlot.setLocationRelativeTo(this);
        releaseSlot.setVisible(true);
    }//GEN-LAST:event_releaseBtnMouseClicked

    private void releaseBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_releaseBtnMouseEntered
        if (releaseBtn.isEnabled()) {
            releaseBtn.setBackground(ParkingSchedular.enterButtonColor);
        }
    }//GEN-LAST:event_releaseBtnMouseEntered

    private void releaseBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_releaseBtnMouseExited
        if (releaseBtn.isEnabled()) {
            releaseBtn.setBackground(ParkingSchedular.buttonColor);
        }
    }//GEN-LAST:event_releaseBtnMouseExited

    private void payBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payBtnMouseClicked
        String arr[] = ParkingSchedular.time.split(":");
        int hh = Integer.parseInt(arr[0]);
        if (arr[2].contains("PM")) {
            hh = Integer.parseInt(arr[0]) + 12;
        } else if (hh == 12) {
            hh = 0;
        }
        String tString = ParkingSchedular.date + " " + hh + ":" + arr[1] + ":" + arr[2].split(" ")[0];
        ParkingSchedular.server.releaseSlot(slotsMenu.getSelectedIndex(), userTable, tString, chargeLabel.getText());
        intializeDetails();
        releaseSlot.setVisible(false);
    }//GEN-LAST:event_payBtnMouseClicked

    private void payBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payBtnMouseEntered
        if (payBtn.isEnabled()) {
            payBtn.setBackground(ParkingSchedular.enterButtonColor);
        }
    }//GEN-LAST:event_payBtnMouseEntered

    private void payBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payBtnMouseExited
        if (payBtn.isEnabled()) {
            payBtn.setBackground(ParkingSchedular.buttonColor);
        }
    }//GEN-LAST:event_payBtnMouseExited

    private void slotsMenuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_slotsMenuFocusGained
        updateTotalCharge();
    }//GEN-LAST:event_slotsMenuFocusGained

    private void slotsMenuPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_slotsMenuPopupMenuWillBecomeInvisible
        updateTotalCharge();
    }//GEN-LAST:event_slotsMenuPopupMenuWillBecomeInvisible

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnCloseMouseClicked
        System.exit(0);
    }// GEN-LAST:event_btnCloseMouseClicked

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnCloseMouseEntered
        btnClose.setIcon(u.imageCloseh);
    }// GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExit(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnCloseMouseExit
        btnClose.setIcon(u.imageClose);
    }// GEN-LAST:event_btnCloseMouseExit

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - u.xMouse, y - u.yMouse);
    }// GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanel1MousePressed
        u.xMouse = evt.getX();
        u.yMouse = evt.getY();
    }// GEN-LAST:event_jPanel1MousePressed

    private void nameTextFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_nameTextFocusGained
        u.fieldFocused(nameText);
    }// GEN-LAST:event_nameTextFocusGained

    private void nameTextFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_nameTextFocusLost
        u.fieldLeave(nameText);
    }// GEN-LAST:event_nameTextFocusLost

    private void vehicleTextFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_vehicleTextFocusGained
        u.fieldFocused(vehicleText);
    }// GEN-LAST:event_vehicleTextFocusGained

    private void vehicleTextFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_vehicleTextFocusLost
        u.fieldLeave(vehicleText);
    }// GEN-LAST:event_vehicleTextFocusLost

    private void bookBtnMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_bookBtnMouseClicked
        bookBtn.setBackground(new Color(204, 204, 204));
        if (nameText.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please fill out your name.");
        } else if (vehicleText.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please fill out vehicle number.");
        } else if (dateText.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please fill out arrival date.");
        } else if (timeText.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please fill out arrival time.");
        } else {
            int vehicleType = 0;
            if (motorcycleRadio.isSelected()) {
                vehicleType = 1;
            }
            String arr[] = timeText.getText().split(":");
            int hh = Integer.parseInt(arr[0]);
            if (arr[2].contains("PM")) {
                hh = Integer.parseInt(arr[0]) + 12;
            } else if (hh == 12) {
                hh = 0;
            }
            String time = dateText.getText() + " " + hh + ":" + arr[1] + ":" + arr[2].split(" ")[0];
            int result = ParkingSchedular.server.bookSlot(Integer.parseInt(slotText.getText()), nameText.getText(),
                    vehicleText.getText(), time, "pending", vehicleType);
            if (result == -1) {
                JOptionPane.showMessageDialog(null, "Failed to establish connection with server!", "Connection Failed", ERROR_MESSAGE);
            } else if (result == 0) {
                JOptionPane.showMessageDialog(this, "Slot alredy booked");
            } else {
                JOptionPane.showMessageDialog(this,
                        "Slot " + slotText.getText() + " booked sucessfully");
            }
        }
        intializeDetails();
    }// GEN-LAST:event_bookBtnMouseClicked

    private void bookBtnMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_bookBtnMouseEntered
        if (bookBtn.isEnabled()) {
            bookBtn.setBackground(ParkingSchedular.enterButtonColor);
        }
    }// GEN-LAST:event_bookBtnMouseEntered

    private void bookBtnMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_bookBtnMouseExited
        if (bookBtn.isEnabled()) {
            bookBtn.setBackground(ParkingSchedular.buttonColor);
        }
    }// GEN-LAST:event_bookBtnMouseExited

    public String takeInputs(JLabel l, String msg) {
        String str = JOptionPane.showInputDialog(this, msg);
        return str.equals("") ? l.getText() : str;
    }

    private void updateDetailsMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_updateDetailsMouseClicked
        Name.setText(takeInputs(Name, "Enter Name: "));
        Vehicle.setText(takeInputs(Vehicle, "Enter Vehicle Number: "));
        Email.setText(takeInputs(Email, "Enter Email: "));
        Phone.setText(takeInputs(Phone, "Enter Vehicle Number: "));
        int type = (JOptionPane.showInputDialog(this, "Enter Vehicle Type(car/motorcycle): ")).equals("car") ? 0 : 1;
        ParkingSchedular.server.updateUserDetails(Name.getText(), Phone.getText(), Email.getText(), Vehicle.getText(),
                type);
        ParkingSchedular.Email = Email.getText();
        u.switchFrame(this, ParkingSchedular.udg);
        ParkingSchedular.udg.intializeDetails();
    }// GEN-LAST:event_updateDetailsMouseClicked

    private void updateDetailsMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_updateDetailsMouseEntered
        if (updateDetails.isEnabled()) {
            updateDetails.setBackground(ParkingSchedular.enterButtonColor);
        }
    }// GEN-LAST:event_updateDetailsMouseEntered

    private void updateDetailsMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_updateDetailsMouseExited
        if (updateDetails.isEnabled()) {
            updateDetails.setBackground(ParkingSchedular.buttonColor);
        }
    }// GEN-LAST:event_updateDetailsMouseExited

    private void dateTextFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_dateTextFocusGained
        u.fieldFocused(dateText);
    }// GEN-LAST:event_dateTextFocusGained

    private void dateTextFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_dateTextFocusLost
        u.fieldLeave(dateText);
    }// GEN-LAST:event_dateTextFocusLost

    private void timeTextFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_timeTextFocusGained
        u.fieldFocused(timeText);
    }// GEN-LAST:event_timeTextFocusGained

    private void timeTextFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_timeTextFocusLost
        u.fieldLeave(timeText);
    }// GEN-LAST:event_timeTextFocusLost

    private void clockMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_clockMouseClicked
        initializeTime();
    }// GEN-LAST:event_clockMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDashboardGUI.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDashboardGUI.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDashboardGUI.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDashboardGUI.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new UserDashboardGUI().setVisible(true);
            }
        });
    }

    public void login() {
        t = new Time();
        t.start(timeT, dateT);
        intializeDetails();
    }

    public void intializeDetails() {
        UD = ParkingSchedular.server.userDetails(ParkingSchedular.Email);
        Email.setText(UD.getEmail());
        Name.setText(UD.getName());
        Phone.setText(UD.getPhone());
        Vehicle.setText(UD.getVehicle());
        Email.setText(UD.getEmail());
        nameText.setText(UD.getName());
        vehicleText.setText(UD.getVehicle());
        motorcycleRadio.setSelected(!(UD.getVehicleType().equals("Car")));
        int slot = ParkingSchedular.server.getAvailableSlot();
        if (slot >= 0) {
            slotText.setText(slot + 1 + "");
        }
        userTable.setDefaultRenderer(Object.class, new CustomRowRenderer());
        ParkingSchedular.server.getSlotTable(userTable, slotsMenu);
        initializeTime();
    }

    public void initializeTime() {
        dateText.setText(ParkingSchedular.date);
        timeText.setText(ParkingSchedular.time);
    }

    public void updateTotalCharge() {
        try {
            String startTime = userTable.getValueAt(slotsMenu.getSelectedIndex(), 3).toString();
            String arr[] = startTime.split(" ");
            String date[] = arr[0].split("/");
            String time[] = arr[1].split(":");
            int iarr[] = new int[6];
            for (int i = 0; i < 3; i++) {
                iarr[i] = Integer.parseInt(date[i]);
            }
            for (int i = 3; i < 6; i++) {
                iarr[i] = Integer.parseInt(time[i - 3]);
            }
            LocalDateTime startDate = LocalDateTime.of(iarr[2], iarr[1], iarr[0], iarr[3], iarr[4], iarr[5]);
            long hours = Duration.between(startDate, ParkingSchedular.currentTime).toHours() + 1;
            chargeLabel.setText("Rs. " + (hours * 40));
        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println(e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Lemail;
    private javax.swing.JLabel Lname;
    private javax.swing.JLabel Lvehicle;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Phone;
    private javax.swing.JLabel Vehicle;
    private javax.swing.JButton bookBtn;
    private javax.swing.JLabel btnClose;
    private parkingschedular.utility.RadioButtonCustom carRadio;
    private javax.swing.JLabel chargeL;
    private javax.swing.JLabel chargeLabel;
    private javax.swing.JLabel chargeLabel1;
    private javax.swing.JLabel chargeT;
    private javax.swing.JLabel clock;
    private javax.swing.JLabel date;
    private javax.swing.JLabel dateL;
    private javax.swing.JLabel dateT;
    private javax.swing.JFormattedTextField dateText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lPhone;
    private javax.swing.JButton logOut;
    private parkingschedular.utility.RadioButtonCustom motorcycleRadio;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nameText;
    private javax.swing.JButton payBtn;
    private javax.swing.JButton releaseBtn;
    private javax.swing.JDialog releaseSlot;
    private javax.swing.JLabel selectedSlotL;
    private javax.swing.JLabel slot;
    private javax.swing.JTextField slotText;
    private javax.swing.JComboBox<String> slotsMenu;
    private javax.swing.JLabel time;
    private javax.swing.JLabel timeL;
    private javax.swing.JLabel timeT;
    private javax.swing.JFormattedTextField timeText;
    private javax.swing.JLabel tittle;
    private javax.swing.JButton updateDetails;
    private javax.swing.JTable userTable;
    private javax.swing.JLabel vehicle;
    private javax.swing.JTextField vehicleText;
    private javax.swing.JLabel vehicleType;
    private javax.swing.ButtonGroup vehicleTypeGroup;
    // End of variables declaration//GEN-END:variables
}

class CustomRowRenderer extends DefaultTableCellRenderer {

    @Override
    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus,
            int row, int column) {
        Component component = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

        // Set the font and color of the row's cells
        component.setFont(new Font("Yu Gothic UI", 0, 16));
        ((JLabel) component).setHorizontalAlignment(SwingConstants.CENTER);
        component.setForeground(new java.awt.Color(255, 255, 255));

        return component;
    }
}
